// RTM: the requirements-traceability view promised in 08 §4 — a generated,
// never-source rendering of the chain the contracts already enforce:
// requirement → AC → verification-strategy → grounded test evidence →
// ac-verdict → tasks → loops. Views never gate (07 §5); this is the
// human/auditor-facing artifact of the machine-checked chain.
package views

import (
	"fmt"
	"sort"
	"strings"

	"github.com/dariusz-klibisz/ClaudeWorkflow/engine/internal/runctl"
)

// RTM renders the requirements-traceability matrix for the active run as
// markdown. Pure read — no records are written.
func RTM(c *runctl.Ctl) (string, error) {
	r, err := c.MustRun()
	if err != nil {
		return "", err
	}
	env, err := c.Env(r)
	if err != nil {
		return "", err
	}

	// fold the evidence chain per AC id
	type acEvidence struct {
		strategies []string // "method: command"
		greens     int      // grounded green test-runs tagged with the AC
		reds       int      // grounded red test-runs tagged with the AC
		manual     int      // ungrounded (self-attested) tagged test-runs
		verdict    string   // folded ac-verdict status
		tasks      []string
		loops      []string // causes
	}
	ev := map[string]*acEvidence{}
	get := func(ac string) *acEvidence {
		if ev[ac] == nil {
			ev[ac] = &acEvidence{}
		}
		return ev[ac]
	}

	for _, s := range env.Records("verification-strategy") {
		ac, _ := s.Data["ac"].(string)
		if ac == "" {
			continue
		}
		line, _ := s.Data["method"].(string)
		if cmd, _ := s.Data["command"].(string); cmd != "" {
			line += ": `" + cmd + "`"
		}
		get(ac).strategies = append(get(ac).strategies, line)
	}
	for _, tr := range env.Records("test-run") {
		ac, _ := tr.Data["ac"].(string)
		if ac == "" {
			continue
		}
		grounded, _ := tr.Data["grounded"].(bool)
		exit := numOr(tr.Data["exit"], -1)
		switch {
		case !grounded:
			get(ac).manual++
		case exit == 0:
			get(ac).greens++
		default:
			get(ac).reds++
		}
	}
	for _, v := range env.Records("ac-verdict") {
		ac, _ := v.Data["ac"].(string)
		if ac == "" {
			continue
		}
		get(ac).verdict, _ = v.Data["status"].(string)
	}
	for _, t := range env.Records("task") {
		tid, _ := t.Data["tid"].(string)
		links, _ := t.Data["ac_links"].([]any)
		for _, l := range links {
			if ac := fmt.Sprintf("%v", l); ac != "" {
				get(ac).tasks = append(get(ac).tasks, tid)
			}
		}
	}
	for _, l := range env.Records("loop") {
		ac, _ := l.Data["ac"].(string)
		if ac == "" {
			continue
		}
		cause, _ := l.Data["cause"].(string)
		get(ac).loops = append(get(ac).loops, cause)
	}

	var b strings.Builder
	fmt.Fprintf(&b, "# RTM — run %s (%s/%s)\n\n", r.ID, r.Family, orDashV(r.Intent))
	b.WriteString("Generated by `wf trace --rtm` from the run ledger — a derived view, never hand-edited. The chain it renders is contract-enforced; this file is the auditor-facing rendering, not the enforcement.\n\n")

	reqs := env.Records("requirement")
	if len(reqs) == 0 {
		b.WriteString("no requirement records in this run.\n")
		return b.String(), nil
	}

	seen := map[string]bool{}
	totalACs, groundedACs, passACs := 0, 0, 0
	for _, req := range reqs {
		rid, _ := req.Data["rid"].(string)
		level, _ := req.Data["level"].(string)
		status, _ := req.Data["status"].(string)
		text, _ := req.Data["text"].(string)
		fmt.Fprintf(&b, "## %s — %s\n\n", rid, text)
		fmt.Fprintf(&b, "level: %s · status: %s\n\n", orDashV(level), orDashV(status))
		b.WriteString("| AC | criterion | verification | evidence | verdict | tasks | loops |\n")
		b.WriteString("|----|-----------|--------------|----------|---------|-------|-------|\n")
		acs, _ := req.Data["acs"].([]any)
		for _, raw := range acs {
			m, ok := raw.(map[string]any)
			if !ok {
				continue
			}
			id := fmt.Sprintf("%v", m["id"])
			seen[id] = true
			totalACs++
			e := get(id)
			evidence := evidenceCell(e.greens, e.reds, e.manual)
			if e.greens > 0 {
				groundedACs++
			}
			if e.verdict == "pass" {
				passACs++
			}
			fmt.Fprintf(&b, "| %s | %s | %s | %s | %s | %s | %s |\n",
				id, fmt.Sprintf("%v", m["text"]),
				cell(e.strategies), evidence, orDashV(e.verdict),
				cell(e.tasks), loopCell(e.loops))
		}
		b.WriteString("\n")
	}

	// evidence tagged to ACs no requirement declares — a traceability leak
	var orphans []string
	for ac := range ev {
		if !seen[ac] {
			orphans = append(orphans, ac)
		}
	}
	if len(orphans) > 0 {
		sort.Strings(orphans)
		fmt.Fprintf(&b, "## Unlinked ACs\n\nEvidence or verdicts tagged to ACs no requirement declares: %s\n\n", strings.Join(orphans, ", "))
	}

	fmt.Fprintf(&b, "---\n\nrequirements: %d · ACs: %d · with grounded green evidence: %d · verdict pass: %d · loops: %d · forces: %d\n",
		len(reqs), totalACs, groundedACs, passACs, r.Loops, r.Forces)

	// which baselines the user's approvals bound (engine-computed refs)
	var bound []string
	for _, gate := range []string{"scope", "design", "plan"} {
		for _, a := range env.Records("approval") {
			if g, _ := a.Data["gate"].(string); g != gate {
				continue
			}
			if h, _ := a.Data["refs_hash"].(string); h != "" {
				bound = append(bound, fmt.Sprintf("%s@%s", gate, h))
			}
		}
	}
	if len(bound) > 0 {
		fmt.Fprintf(&b, "approval baselines (refs hash): %s\n", strings.Join(dedupeStr(bound), " · "))
	}
	return b.String(), nil
}

func dedupeStr(in []string) []string {
	seen := map[string]bool{}
	var out []string
	for _, s := range in {
		if !seen[s] {
			seen[s] = true
			out = append(out, s)
		}
	}
	return out
}

func evidenceCell(greens, reds, manual int) string {
	var parts []string
	if greens > 0 {
		parts = append(parts, fmt.Sprintf("%d grounded green", greens))
	}
	if reds > 0 {
		parts = append(parts, fmt.Sprintf("%d red", reds))
	}
	if manual > 0 {
		parts = append(parts, fmt.Sprintf("%d self-attested", manual))
	}
	if len(parts) == 0 {
		return "none"
	}
	return strings.Join(parts, ", ")
}

func cell(xs []string) string {
	if len(xs) == 0 {
		return "—"
	}
	return strings.Join(xs, ", ")
}

func loopCell(causes []string) string {
	if len(causes) == 0 {
		return "—"
	}
	return fmt.Sprintf("%d (%s)", len(causes), strings.Join(causes, ", "))
}

func orDashV(s string) string {
	if s == "" {
		return "—"
	}
	return s
}

// numOr coerces JSON/YAML numbers.
func numOr(v any, def float64) float64 {
	switch n := v.(type) {
	case float64:
		return n
	case int:
		return float64(n)
	case int64:
		return float64(n)
	}
	return def
}
